apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: prova-1-devops
  newName: prova-1-devops
  newTag: d61f04e81b3dca0a7ec63bb5ba03f82ade2e0a33
