apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: prova-1-devops
  newName: gbrlls/prova-1-devops
  newTag: 2f8b64591eacbc147bc4efe448bb791778028da0
